### ISSUE TITLE
Code exercice lundi

### ISSUE THREAD

**Issue by LionelPaulus** [neopixl/hetic2017h4#1]
Bonjour,

Serait-il possible de publier le code de l'exercice avec la recherche de films via API que nous avons réalisé lundi ?

Merci d'avance 😃

**Comment by AlonsoFloo** [comment]
Je l'ai pas sous la main là de suite, mais je le fait ASAP.

**Comment by AlonsoFloo** [comment]
Fait sur la branche "android-exo" ;)
